[project]
name = "odia-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.13.0",
    "onnx==1.20.1",
    "onnxruntime==1.20.1",
    "onnxruntime-gpu==1.20.1",
    "peft>=0.19.1",
    "pillow>=12.2.0",
    "python-docx>=1.2.0",
    "pytesseract>=0.3.13",
    "silero-vad>=6.2.1",
    "soundfile>=0.13.1",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=5.5.4",
    "python-dotenv>=1.2.2",
    "pydub>=0.25.1",
]
